server:
  port: 8089

spring:
  application:
    name: apigateway

  # Evita errores si no tienes Zipkin corriendo
  zipkin:
    enabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/nomelestar/protocol/openid-connect/certs

  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://product-service:8084
          predicates:
            - Path=/api/products/**
        - id: order-service
          uri: http://order-service:8083
          predicates:
            - Path=/api/orders/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
