server:
  port: 8083
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://postgres.default.svc.cluster.local:5432/orders
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    serviceURL:
      default: http://eureka.default.svc.cluster.local:8761/eureka/
    fetch-registry: true