server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://postgres.default.svc.cluster.local:5432/users
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceURL:
      default: http://eureka.default.svc.cluster.local:8761/eureka/
    fetch-registry: true