apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigetaway
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigetaway
  template:
    metadata:
      labels:
        app: apigetaway
    spec:
      containers:
        - name: apigetaway
          image: apigetaway:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8089
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka:8761/eureka/"
            - name: SPRING_CONFIG_IMPORT
              value: "configserver:http://serversc:8888"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8089
            initialDelaySeconds: 40
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8089
            initialDelaySeconds: 60
            periodSeconds: 15
