apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  ports:
    - port: 8083
      targetPort: 8083
  selector:
    app: order-service
  type: ClusterIP
