apiVersion: v1
kind: Service
metadata:
  name: apigateway
  labels:
    app: apigateway
spec:
  ports:
    - port: 8089
      targetPort: 8089
      # Opcional: Para tu clase tal vez quieras exponerlo directamente (LoadBalancer o NodePort)
      # type: LoadBalancer
  selector:
    app: apigateway
  type: LoadBalancer
